# Test your FastAPI endpoints

# Test summarize endpoint with a sample string
GET http://127.0.0.1:8000/Summarize/This%20is%20a%20sample%20text%20that%20should%20be%20summarized.
Accept: application/json
###

# Test get_summaries endpoint
GET http://127.0.0.1:8000/get_summaries
Accept: application/json

###
